# https://docs.microsoft.com/azure/devops/pipelines/languages/android
parameters:
  script: 'npx mocha --timeout 6000000 --recursive build/test/functional/'
  workingDirectory: ''
  name: ''
  dependsOn: ''
  chromedriverVersion: '2.44'
  nodeVersion: '11.x'
  testResultsFiles: 'junit-test-results.xml'

jobs:
  - job: ${{ parameters.name }}
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      vmImage: 'macOS-10.13'
    variables:
      TERM: dumb
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.nodeVersion }}
    - script: npm install --chromedriver_version="${{ parameters.chromedriverVersion }}"
      workingDirectory: ${{ parameters.workingDirectory }}
      displayName: Install Node dependencies
    - script: npm install -g mjpeg-consumer
      displayName: Install MJPEG Consumer
    - script: bash ci/start-emulator.sh
      displayName: Create and run Emulator
    - script: npm run build
      workingDirectory: ${{ parameters.workingDirectory }}
      displayName: Build
    - script: ${{ parameters.script }}
      workingDirectory: ${{ parameters.workingDirectory }}
      displayName: Run tests
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: ${{ parameters.testResultsFiles }}
 
