# https://docs.microsoft.com/azure/devops/pipelines/languages/android
pool:
  vmImage: 'macOS-10.13'
variables:
  TERM: dumb
steps:
#- task: Gradle@2
  #inputs:
    #workingDirectory: 'packages/appium-espresso-driver/espresso-server'
    #gradleWrapperFile: '\gradlew'
    #gradleOptions: '-Xmx3072m'
    #publishJUnitResults: false
- script: bash ci/start-emulator.sh
  displayName: Create and Build Emulator
- task: NodeTool@0
  inputs:
    versionSpec: 11.x
- script: npx lerna bootstrap
  displayName: Lerna bootstrap
#- script: npm test
  #displayName: Run tests
- script: npm run build
  workingDirectory: packages/appium-espresso-driver
  displayName: Build
- script: npx mocha --timeout 6000000 --recursive packages/appium-espresso-driver/build/test/functional/
  displayName: Espresso Driver E2E Tests
