# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:
  - template: ci/android/android-e2e-template.yml
    parameters:
      name: EspressoDriverE2E
      script: npx mocha --timeout 6000000 --recursive build/test/functional/
      workingDirectory: packages/appium-espresso-driver


