jobs:
  - job: UnitTests
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 11.x
      - script: npm install
        displayName: Install dependencies
      - script: npx lerna bootstrap --no-ci
      - script: npx lerna run test
