parameters:
  node_version: 11.x
  name: Node11Tests
jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ${{ parameters.node_version }}
      - script: npm install
        displayName: Install dependencies
      - script: npx lerna bootstrap --no-ci
        displayName: Lerna Bootstrap
      - script: npx lerna run test
        displayName: Run npm test on all packages