jobs:
  - job: E2E_Basic_12_2
    pool:
      vmImage: 'macOS 10.13'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 11.x
    - script: npm install
      workingDirectory: packages/appium-xcuitest-driver
      displayName: Install node dependencies
    - script: npm run build
      workingDirectory: packages/appium-xcuitest-driver
      displayName: Build
    - script: npx mocha --timeout 480000 build/test/functional -g @skip-ci -i --exit
      workingDirectory: packages/appium-xcuitest-driver
      displayName: Run functional tests
