jobs:
  - template: ../../ci/ios/ios-e2e-template.yml
    parameters:
      name: e2e_basic_10_0
      script: |
        npm install --no-save mjpeg-consumer
        npx mocha --timeout 480000 --recursive build/test/functional/basic -g @skip-ci -i --exit
      workingDirectory: packages/appium-xcuitest-driver

  - template: ../../ci/ios/ios-e2e-template.yml
    parameters:
      name: e2e_driver_10_0
      script: npx mocha --timeout 480000 --recursive build/test/functional/driver -g @skip-ci -i --exit
      workingDirectory: packages/appium-xcuitest-driver

  - template: ../../ci/ios/ios-e2e-template.yml 
    parameters:
      name: e2e_web_10_0
      script: npx mocha --timeout 480000 --recursive build/test/functional/web -g @skip-ci -i --exit
      workingDirectory: packages/appium-xcuitest-driver

  - template: ../../ci/ios/ios-e2e-template.yml
    parameters:
      name: e2e_long_10_0
      script: npx mocha --timeout 480000 --recursive build/test/functional/long -g @skip-ci -i --exit
      workingDirectory: packages/appium-xcuitest-driver

  
