jobs:
  - template: ../../ci/ios/ios-e2e-template.yml
    parameters:
      script: npx mocha --timeout 480000 --recursive build/test/functional/basic -g @skip-ci -i --exit
      workingDirectory: packages/appium-xcuitest-driver
  
